# Generated by Django 5.2.7 on 2025-11-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progreso',
        ),
    ]
